### ISSUE TITLE
How can I use pygraft for my own data?

### ISSUE THREAD

**Issue by Hangsiin** [nicolas-hbt/pygraft#1]
Hi! 
Thank you for open-sourcing your interesting research. 
What I'm wondering is how I can use this code to create a knowledge graph of the data I have. 
If I had an organized excel file in tabular format, would it be possible to use that? 
I have very little knowledge in this area, so I apologize if my question is too low level.
Thanks.

**Comment by nicolas-hbt** [comment]
Hi Hangsiin,

Thank you for your interest in PyGraft. At the moment, PyGraft allows you to : 
(1) create a schema (e.g. an ontology) from scratch, based on a configuration file specifying its main characteristics (e.g. the number of classes and relations you want, but also the proportion of symmetric, transitive, reflexive, etc. relations)
(2) create a knowledge graph (KG) based on an exisiting schema (in most cases, the one you just generate at step (1)).
Note that for now, PyGraft needs the schema to be formatted in a specific way so that it can be included in the KG generation pipeline. In future versions of PyGraft, we will enable support for **any** input schema. We just chose not to do it in the initial version, because this is actually something you can already do with other existing Python libraries.

Now, your problem is quite different: you already have data in tabular format, and my understanding is that your data are specific instances/individuals, right? In this case, you do not really need PyGraft, as **you do not want to generate new, synthetic data**. You just want to convert your tabular data into a KG-based format. To this respect, my go-to approach would simply be to use Pandas to merge and aggregate your existing data into one single DataFrame, and then use [rdflib](https://github.com/RDFLib/rdflib) to serialize it as a KG, in whatever format best suits you.

I hope this helps!

**Comment by Hangsiin** [comment]
Thanks for detail explanation.
As your reply, this tool looks very useful when I want to synthesis new data.
I'll try to use PyGraft after study more about KG.
And thanks again for introducing rdfilb!
